import { describe, it, expect } from "vitest";
import { wagonGroups, wagons, groupFeatures } from "@/lib/sturtuvagnar";

// Mockup 1 (product pages) needs per-product blurb copy + a card image, and
// per-group product lists + the hjólagröfuvagnar-only feature tiles — all
// generated by scripts/gen-sturtuvagnar.mjs from the existing scrape JSON
// (docs/scrape/sturtuvagnar__*.json / docs/scrape/sturtuvagnar.json), never
// hand-authored. These guard that generator's output.
describe("lib/sturtuvagnar generated data", () => {
  it("every wagon has a non-empty blurb and a cardImage under /images/", () => {
    for (const wagon of wagons) {
      expect(wagon.blurb, `${wagon.slug}: blurb`).toBeTruthy();
      expect(
        wagon.cardImage?.src.startsWith("/images/"),
        `${wagon.slug}: cardImage.src`,
      ).toBe(true);
    }
  });

  it("every group's products list is exactly the wagons with that groupId", () => {
    for (const group of wagonGroups) {
      const expected = wagons
        .filter((w) => w.groupId === group.id)
        .map((w) => w.slug)
        .sort();
      expect([...group.products].sort(), group.id).toEqual(expected);
    }
  });

  it("groupFeatures.hjolagrofuvagnar has exactly 7 items", () => {
    expect(groupFeatures.hjolagrofuvagnar.items).toHaveLength(7);
    expect(groupFeatures.hjolagrofuvagnar.heading).toBeTruthy();
  });
});
